# Generated by Django 4.1.2 on 2022-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=32)),
                ('passw', models.CharField(max_length=64)),
                ('gen', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('Compname', models.CharField(max_length=32)),
            ],
        ),
    ]
