# Generated by Django 4.1.2 on 2022-12-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Compname',
            new_name='compname',
        ),
    ]
